bakaapp/urls.py
from django.urls import path
from .views import *


app_name = "bakaapp"
urlpatterns = [
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('med-client/service/list',
         ClientServiceListView.as_view(), name="clientservicelist"),
    path('med-client/service/<int:pk>/detail',
         ClientServiceDetailView.as_view(), name="clientservicedetail"),
    path('med-client/servicepackages/list',
         ClientServicePackageListView.as_view(),
         name="clientservicepackagelist"),
    path('med-client/servicepackage/<int:pk>/detail',
         ClientServicePackageDetailView.as_view(),
         name="clientservicepackagedetail"),
    path('med-client/offer/list',
         ClientOfferListView.as_view(),
         name="clientofferlist"),
    path('med-client/offer/<int:pk>/detail',
         ClientOfferDetailView.as_view(),
         name="clientofferdetail"),
    path('servicepackage/<int:pk>/book/',
         ClientServicePackageBookingView.as_view(),
         name="clientservicepackagebooking"),


    # admin login
    path('med-admin/login/', AdminLoginView.as_view(), name="adminlogin"),
    path('med-admin/logout/', AdminLogoutView.as_view(), name="adminlogout"),
    # admin service
    path('med-admin/home/', AdminHomeView.as_view(), name="adminhome"),
    path('med-admin/service/create/',
         AdminServiceCreate.as_view(), name="adminservicecreate"),
    path('med-admin/service/list/', AdminServiceListView.as_view(),
         name="adminservicelist"),
    path('med-admin/service/<int:pk>/update/',
         AdminServiceUpdateView.as_view(), name="adminserviceupdate"),
    path('med-admin/service/<int:pk>/delete/',
         AdminServiceDeleteView.as_view(), name="adminservicedelete"),
    # admin servicepackage
    path('med-admin/servicepackage/list/',
         AdminServicePackageListView.as_view(),
         name="adminservicepackagelist"),
    path('med-admin/servicepackage/create/',
         AdminServicePackageCreateView.as_view(),
         name='adminservicepackagecreate'),
    path('med-admin/servicepackage/<int:pk>/update/',
         AdminServicePackageUpdateView.as_view(),
         name="adminservicepackageupdate"),
    path('med-admin/servicepackage/<int:pk>/delete/',
         AdminServicePackageDeleteView.as_view(),
         name="adminservicepackagedelete"),
    # admin offer
    path('med-admin/offer/create/',
         AdminOfferCreateView.as_view(), name="adminoffercreate"),
    path('med-admin/offer/list/', AdminOfferListView.as_view(),
         name="adminofferlist"),
    path('med-admin/offer/<int:pk>/update/',
         AdminOfferUpdateView.as_view(), name="adminofferupdate"),
    path('med-admin/offer/<int:pk>/delete/',
         AdminOfferDeleteView.as_view(), name="adminofferdelete"),
    # admin album
    path('med-admin/album/create/',
         AdminAlbumCreateView.as_view(), name="adminalbumcreate"),
    path('med-admin/album/list/', AdminAlbumListView.as_view(),
         name="adminalbumlist"),
    path('med-admin/album/<int:pk>/update/',
         AdminAlbumUpdateView.as_view(), name="adminalbumupdate"),
    path('med-admin/album/<int:pk>/delete/',
         AdminAlbumDeleteView.as_view(), name="adminalbumdelete"),
    # admin team
    path('med-admin/team/create/',
         AdminTeamCreateView.as_view(), name="adminteamcreate"),
    path('med-admin/team/list/', AdminTeamListView.as_view(),
         name="adminteamlist"),
    path('med-admin/team/<int:pk>/update/',
         AdminTeamUpdateView.as_view(), name="adminteamupdate"),
    path('med-admin/team/<int:pk>/delete/',
         AdminTeamDeleteView.as_view(), name="adminteamdelete"),





]

bakaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('bakaapp.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Grand Tour Travel Category Flat Bootstrap Responsive Web Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Grand Tour Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
	
	<!-- css files -->
    <link href="{% static 'clientstatic/css/bootstrap.css' %}"rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="{% static 'clientstatic/css/style.css' %}"rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="{% static 'clientstatic/css/font-awesome.min.css' %}"rel="stylesheet"><!-- fontawesome css -->
	<!-- //css files -->
	
	<link href="{% static 'clientstatic/css/css_slider.css' %}"type="text/css" rel="stylesheet" media="all">

	<!-- google fonts -->
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<!-- //google fonts -->
	
</head>
<body>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5d36bd916d80831228398bfa/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
<!-- header -->
<header>
	<div class="container">
		<!-- nav -->
		<nav class="py-md-4 py-3 d-lg-flex">
			<div id="logo">
				<h1 class="mt-md-0 mt-2"> <a href="{% url 'bakaapp:clienthome' %}"><span class="fa fa-map-signs"></span>Lion Nepal Travels And Tours</a></h1>
			</div>
			<label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
			<input type="checkbox" id="drop" />
			<ul class="menu ml-auto mt-1">
				<li class="active"><a href="{% url 'bakaapp:clienthome' %}">Home</a></li>
				<li class=""><a href="about.html">About Us</a></li>
				<li class=""><a href="{% url 'bakaapp:clientservicelist' %}">Services</a></li>
				<li class=""><a href="{% url 'bakaapp:clientservicepackagelist' %}">Service Packages</a></li>
				<li class=""><a href="contact.html">Contact</a></li>
				<li class="booking"><a href="booking.html">Book Now</a></li>
			</ul>
		</nav>
		<!-- //nav -->
	</div>
</header>
<!-- //header -->







{% block content %}


{% endblock %}





<!--footer -->
<footer>
<section class="footer footer_w3layouts_section_1its py-5">
	<div class="container py-lg-4 py-3">
		<div class="row footer-top">
			<div class="col-lg-3 col-sm-6 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>Address</h3>
				</div>
				<div class="footer-text">
					<p>Location : 1234 lock, Charlotte, North Carolina, United States</p>
					<p>Phone : +12 534894364</p>
					<p>Email : <a href="mailto:info@example.com">info@example.com</a></p>
					<p>Fax : +12 534894364</p>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 footer-grid_section mt-sm-0 mt-4">
				<div class="footer-title">
					<h3>About Us</h3>
				</div>
				<div class="footer-text">
					<p>Vivamus magna justo, laci niats eget consectetur sed, conval lis at tellus. Nulla quis lorem ipnt libero.
					Lorem ipsum dolor.</p>
				</div>
				<ul class="social_section_1info">
					<li class="mb-2 facebook"><a href="#"><span class="fa fa-facebook"></span></a></li>
					<li class="mb-2 twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
					<li class="google"><a href="#"><span class="fa fa-google-plus"></span></a></li>
					<li class="linkedin"><a href="#"><span class="fa fa-linkedin"></span></a></li>
				</ul>
			</div>
			<div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>Travel Places</h3>
				</div>
				<div class="row">
					<ul class="col-6 links">
						<li><a href="#choose" class="scroll">New Zealand </a></li>
						<li><a href="#overview" class="scroll">Paris, France </a></li>
						<li><a href="#pricing" class="scroll">Los Angles</a></li>
						<li><a href="#faq" class="scroll"> Darlington</a></li>
						<li><a href="#testimonials" class="scroll">Canada </a></li>
						<li><a href="#contact" class="scroll"> South Africa </a></li>
					</ul>
					<ul class="col-6 links">
						<li><a href="#">Spain </a></li>
						<li><a href="#">Turkey </a></li>
						<li><a href="#faq" class="scroll">Europe </a></li>
						<li><a href="#">Italy </a></li>
						<li><a href="#">Sweden </a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>Newsletter</h3>
				</div>
				<div class="footer-text">
					<p>By subscribing to our mailing list you will always get latest news and updates from us.</p>
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter your email..." required="">
						<button class="btn1"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
						<div class="clearfix"> </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
</footer>
<!-- //footer -->

<!-- copyright -->
<div class="copyright py-3 text-center">
	<p>© 2019 Grand Tour. All Rights Reserved | Design by <a href="http://w3layouts.com/" target="=_blank"> W3layouts </a></p>
</div>
<!-- //copyright -->

<!-- move top -->
<div class="move-top text-right">
	<a href="#home" class="move-top"> 
		<span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
	</a>
</div>
<!-- move top -->

	
</body>
</html>

templates/clienttemplates/clientofferdetail.html
{% extends 'clienttemplates/clientbase.html' %}


{% load static %}


{% block content %}

<!-- banner -->
<section class="banner_inner" id="home">
	<div class="banner_inner_overlay">
	</div>
</section>
<!-- //banner -->

<!-- about -->
<section class="about py-5">
	<div class="container py-lg-5 py-sm-4">
		<div class="row">
			<div class="col-lg-6 about-left">
				<h3 class="mt-lg-3">{{ offerdetail.title }} <strong>Explore with us!</strong></h3>
				<p class="mt-4">{{ offerdetail.details }}</p>
<!-- 				<p class="mt-3"> Donec a arcu et sapien hendrerit accumsan. Pellentesque sit amet eros iac, elementum 
				urna ipsum accumsan, iaculis ligula. Aenean quam eget maximus in convallis felis dapibus sit amet.</p> -->
			</div>
			<div class="col-lg-6 about-right text-lg-right mt-lg-10 mt-5">
				<img src="{{ servicedetail.image.url }}" alt="" class="img-fluid abt-image" />
			</div>
		</div>
		<div class="row mt-5 text-center">
			<div class="col-lg-3 col-6">
				<div class="counter">
					<span class="fa fa-smile-o"></span>
					<div class="timer count-title count-number">1000+</div>
					<p class="count-text text-uppercase">happy customers</p>
				</div>
			</div>
			<div class="col-lg-3 col-6">
				<div class="counter">
					<span class="fa fa-ship"></span>
					<div class="timer count-title count-number">2271</div>
					<p class="count-text text-uppercase">Tours & Travels </p>
				</div>
			</div>
			<div class="col-lg-3 col-6 mt-lg-0 mt-5">
				<div class="counter">
					<span class="fa fa-users"></span>
					<div class="timer count-title count-number">200</div>
					<p class="count-text text-uppercase">destinations</p>
				</div>
			</div>
			<div class="col-lg-3 col-6 mt-lg-0 mt-5">
				<div class="counter">
					<span class="fa fa-gift"></span>
					<div class="timer count-title count-number">20+<span>years</span></div>
					<p class="count-text text-uppercase">experience</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //about -->

{% endblock %}

templates/clienttemplates/clientofferlist.html
{% extends 'clienttemplates/clientbase.html' %}


{% load static %}


{% block content %}
<!-- banner -->
<section class="banner_inner" id="home">
	<div class="banner_inner_overlay">
	</div>
</section>
<!-- //banner -->

<!-- services -->
<section class="services pt-5">
	<div class="container py-lg-5 py-sm-3">
		<h2 class="heading text-capitalize text-center mb-lg-5 mb-4">Our Services</h2>
		<div class="row">
			<div class="col-lg-3 main-title-text">
				<h4 class="my-lg-4 mb-4">The journey of a thousand miles begins with a single step.</h4>
				<img src="images/p1.jpg" alt="" class="img-fluid" />
			</div>
			<div class="col-lg-9 mt-lg-0 mt-5">
				<div class="row">
					{% for offer in clientofferlist %}
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="ser-sevice-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-users" aria-hidden="true"></span>
							</div>
							  <h4 class="pb-3">{{ offer.title }}</h4>
							  
								<p>{{ offer.details |truncatechars:"40" }}</p>
								<img src="{{ offer.image.url }}" alt="" class="img-fluid" />
								<a href="{% url 'bakaapp:clientofferdetail' offer.id %}" class="btn-banner"> Read more...</a>
							</div>
					  </div>
					</div>
					{% endfor %}
<!-- 					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-free-code-camp" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Winter Tours</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div> -->
<!-- 					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-users" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Exp Agents</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-money" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Low Prices</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
					  </div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-binoculars" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Easy Booking</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-camera" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Best Packages</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
					  </div>
					</div> -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //services -->
{% endblock %}

templates/clienttemplates/clientservicelist.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}


{% block content %}
<!-- banner -->
<section class="banner_inner" id="home">
	<div class="banner_inner_overlay">
	</div>
</section>
<!-- //banner -->

<!-- services -->
<section class="services pt-5">
	<div class="container py-lg-5 py-sm-3">
		<h2 class="heading text-capitalize text-center mb-lg-5 mb-4">Our Services</h2>
		<div class="row">
			<div class="col-lg-3 main-title-text">
				<h4 class="my-lg-4 mb-4">The journey of a thousand miles begins with a single step.</h4>
				<img src="images/p1.jpg" alt="" class="img-fluid" />
			</div>
			<div class="col-lg-9 mt-lg-0 mt-5">
				<div class="row">
					{% for service in clientservicelist %}
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="ser-sevice-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-users" aria-hidden="true"></span>
							</div>
							  <h4 class="pb-3">{{ service.title }}</h4>
							  
								<p>{{ service.content |truncatechars:"40" }}</p>
								<img src="{{ service.image.url }}" alt="" class="img-fluid" />
								<a href="{% url 'bakaapp:clientservicedetail' service.id %}" class="btn-banner"> Read more...</a>
							</div>
					  </div>
					</div>
					{% endfor %}
<!-- 					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-free-code-camp" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Winter Tours</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div> -->
<!-- 					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-users" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Exp Agents</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-money" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Low Prices</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
					  </div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-binoculars" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Easy Booking</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa fa-camera" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
								<h4 class="pb-3">Best Packages</h4>
							  <p>Duis nisi sapien, elementum et finibus et fermen eget, aliquet etleo. Mauris vel ex.</p>
							</div>
					  </div>
					</div> -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //services -->

{% endblock %}

templates/clienttemplates/clientservicepackagebooking.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<!-- Booking -->
<section class="contact py-5">
	<div class="container py-lg-5 py-sm-4">
		<h2 class="heading text-capitalize text-center mb-lg-5 mb-4"> Book Your Tour</h2>
		<div class="contact-grids">
			<div class="row">
				<div class="col-lg-7 contact-left-form">
					<form action="." method="post" class="row">
						{% csrf_token %}
						<div class="col-sm-6 form-group contact-forms">
						  {{form.name}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
						  {{form.email}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
						  {{form.phone}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
						  {{form.date}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
						  {{form.address}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
							<p>No of adults:</p>
							{{form.adults}}
						</div>
						<div class="col-sm-6 form-group contact-forms">
							{{form.kids}}
						</div>
						<div class="col-md-12 form-group contact-forms">
						  {{form.message}}
						</div>
						<div class="col-md-12 booking-button">
							<button class="btn btn-block sent-butnn"><a href="{% url 'bakaapp:clienthome' %}"></a>
							Book Now</button>
						</div>
					</form>
				</div>
				<div class="col-lg-5 contact-right pl-lg-5">
				
					<div class="image-tour position-relative">
						<img src="images/banner1.jpg" alt="" class="img-fluid" />
						<p><span class="fa fa-tags"></span> <span>20$ - 15% off</span></p>
					</div>
					
					<h4>Tour Description</h4>
					<p class="mt-3">Duis nisi sapien, elementum finibus ferme ntum ed eget, aliquet et leo. Mauris hendrerit vel ex.
					vitae luctus massa. Phas ellus sed aliquam leo et dolor. Vestibulum ullamcorper massa eut sed fringilla.</p>
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //Booking -->

{% endblock %}