bakaapp/urls.py
from django.urls import path
from .views import *


app_name = "bakaapp"
urlpatterns = [
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('med-client/service/list',
         ClientServiceListView.as_view(), name="clientservicelist"),
    path('med-client/service/<int:pk>/detail',
         ClientServiceDetailView.as_view(), name="clientservicedetail"),
    path('med-client/servicepackages/list',
         ClientServicePackageListView.as_view(),
         name="clientservicepackagelist"),
    path('med-client/servicepackage/<int:pk>/detail',
         ClientServicePackageDetailView.as_view(),
         name="clientservicepackagedetail"),
    path('med-client/offer/list',
         ClientOfferListView.as_view(),
         name="clientofferlist"),
    path('med-client/offer/<int:pk>/detail',
         ClientOfferDetailView.as_view(),
         name="clientofferdetail"),
    path('servicepackage/<int:pk>/book/',
         ClientServicePackageBookingView.as_view(),
         name="clientservicepackagebooking"),


    # admin login
    path('med-admin/login/', AdminLoginView.as_view(), name="adminlogin"),
    path('med-admin/logout/', AdminLogoutView.as_view(), name="adminlogout"),
    # admin service
    path('med-admin/home/', AdminHomeView.as_view(), name="adminhome"),
    path('med-admin/service/create/',
         AdminServiceCreate.as_view(), name="adminservicecreate"),
    path('med-admin/service/list/', AdminServiceListView.as_view(),
         name="adminservicelist"),
    path('med-admin/service/<int:pk>/update/',
         AdminServiceUpdateView.as_view(), name="adminserviceupdate"),
    path('med-admin/service/<int:pk>/delete/',
         AdminServiceDeleteView.as_view(), name="adminservicedelete"),
    # admin servicepackage
    path('med-admin/servicepackage/list/',
         AdminServicePackageListView.as_view(),
         name="adminservicepackagelist"),
    path('med-admin/servicepackage/create/',
         AdminServicePackageCreateView.as_view(),
         name='adminservicepackagecreate'),
    path('med-admin/servicepackage/<int:pk>/update/',
         AdminServicePackageUpdateView.as_view(),
         name="adminservicepackageupdate"),
    path('med-admin/servicepackage/<int:pk>/delete/',
         AdminServicePackageDeleteView.as_view(),
         name="adminservicepackagedelete"),
    # admin offer
    path('med-admin/offer/create/',
         AdminOfferCreateView.as_view(), name="adminoffercreate"),
    path('med-admin/offer/list/', AdminOfferListView.as_view(),
         name="adminofferlist"),
    path('med-admin/offer/<int:pk>/update/',
         AdminOfferUpdateView.as_view(), name="adminofferupdate"),
    path('med-admin/offer/<int:pk>/delete/',
         AdminOfferDeleteView.as_view(), name="adminofferdelete"),
    # admin album
    path('med-admin/album/create/',
         AdminAlbumCreateView.as_view(), name="adminalbumcreate"),
    path('med-admin/album/list/', AdminAlbumListView.as_view(),
         name="adminalbumlist"),
    path('med-admin/album/<int:pk>/update/',
         AdminAlbumUpdateView.as_view(), name="adminalbumupdate"),
    path('med-admin/album/<int:pk>/delete/',
         AdminAlbumDeleteView.as_view(), name="adminalbumdelete"),
    # admin team
    path('med-admin/team/create/',
         AdminTeamCreateView.as_view(), name="adminteamcreate"),
    path('med-admin/team/list/', AdminTeamListView.as_view(),
         name="adminteamlist"),
    path('med-admin/team/<int:pk>/update/',
         AdminTeamUpdateView.as_view(), name="adminteamupdate"),
    path('med-admin/team/<int:pk>/delete/',
         AdminTeamDeleteView.as_view(), name="adminteamdelete"),





]

bakaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('bakaapp.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminalbumcreate.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}


{% block content %}

<!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Service Form</h2> -->
            <!--// main-heading -->

            <!-- Forms content -->
            <section class="forms-section">

              
                
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Album Form</h4>
                    <form action="." method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                        <!-- <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                {{form.title}}
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Slug</label>
                                {{form.slug}}
                                
                            </div>
                        </div> -->
                        
                        <button type="submit" class="btn btn-primary">Apply Change Now</button>
                    </form>
                </div>
                <!--// Forms-3 -->
             
            </section>


{% endblock %}

templates/admintemplates/adminalbumdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}

<h3>AdminAlbum Delete </h3>
<form method = "Post">
{% csrf_token %}
<p>Are you Sure To delete?</p>
<button class = "btn btn-danger">yes</button>
<a href="{% url 'bakaapp:adminservicepackagelist' %}" class="btn btn-info"> No</a>
</form>

{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block content %}
 <!--// top-bar -->
            <div class="container-fluid">
                <div class="row">
                    <!-- Stats -->
                    <div class="outer-w3-agile col-xl">
                        <div class="stat-grid p-3 d-flex align-items-center justify-content-between bg-primary">
                            <div class="s-l">
                                <h5>Projects</h5>
                                <p class="paragraph-agileits-w3layouts text-white">Lorem Ipsum</p>
                            </div>
                            <div class="s-r">
                                <h6>340
                                    <i class="far fa-edit"></i>
                                </h6>
                            </div>
                        </div>
                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-success">
                            <div class="s-l">
                                <h5>Clients</h5>
                                <p class="paragraph-agileits-w3layouts">Lorem Ipsum</p>
                            </div>
                            <div class="s-r">
                                <h6>250
                                    <i class="far fa-smile"></i>
                                </h6>
                            </div>
                        </div>
                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-danger">
                            <div class="s-l">
                                <h5>Tasks</h5>
                                <p class="paragraph-agileits-w3layouts">Lorem Ipsum</p>
                            </div>
                            <div class="s-r">
                                <h6>232
                                    <i class="fas fa-tasks"></i>
                                </h6>
                            </div>
                        </div>
                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-warning">
                            <div class="s-l">
                                <h5>Employees</h5>
                                <p class="paragraph-agileits-w3layouts">Lorem Ipsum</p>
                            </div>
                            <div class="s-r">
                                <h6>190
                                    <i class="fas fa-users"></i>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <!--// Stats -->
                    <!-- Pie-chart -->
                    <div class="outer-w3-agile col-xl ml-xl-3 mt-xl-0 mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Pie Chart</h4>
                        <div id="chartdiv"></div>
                    </div>
                    <!--// Pie-chart -->
                </div>
            </div>
            <!-- Simple-chart -->
            <div class="outer-w3-agile mt-3">
                <h4 class="tittle-w3-agileits mb-4">Graph</h4>
                <div id="Hybridgraph" class="simple-chart1">
                </div>
            </div>
            <!--// Simple-chart -->

            <!--// Bar-Chart -->
            <div class="outer-w3-agile mt-3">
                <h4 class="tittle-w3-agileits mb-4">Bar Chart</h4>
                <div id="chart-1"></div>
            </div>
            <!--// Bar-Chart -->

            <!--// three-grids -->
            <div class="container-fluid">
                <div class="row">
                    <!-- Calender -->
                    <div class="outer-w3-agile col-xl mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Multi range Calender</h4>
                        <div class="multi-select-calender"></div>
                        <div class="box"></div>
                    </div>
                    <!--// Calender -->
                    <!-- Profile -->
                    <div class="outer-w3-agile col-xl mt-3 mx-xl-3 p-xl-0 px-md-5">
                        <div class="header">
                            <div class="text">
                                <img src="images/profile.jpg" class="img-fluid rounded-circle" alt="Responsive image">
                                <h2>Matthew Scott</h2>
                                <a href="mailto:info@example.com">
                                    <p>@Lorem ipsum</p>
                                </a>
                            </div>
                        </div>
                        <div class="container-flud">
                            <div class="followers row">
                                <div class="f-left col">
                                    <a href="#">
                                        <i class="far fa-comments"></i>
                                    </a>
                                </div>
                                <div class="f-left col border-left border-right">
                                    <a href="#">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                </div>
                                <div class="f-left col">
                                    <a href="#">
                                        <i class="far fa-heart"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <ul class="prof-widgt-content">
                            <li class="menu">
                                <ul>
                                    <li class="button">
                                        <a href="#">
                                            <i class="fas fa-envelope"></i> Messages
                                            <span>13</span>
                                        </a>
                                    </li>
                                    <li class="dropdown">
                                        <ul class="icon-navigation">
                                            <li>
                                                <a href="#">Inbox
                                                    <span class="float-right">[09]</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">Outbox
                                                    <span class="float-right">[01]</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">Sent messages
                                                    <span class="float-right">[03]</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="menu">
                                <ul>
                                    <li class="button">
                                        <a href="#">
                                            <i class="fas fa-user"></i> Profile</a>
                                    </li>
                                    <li class="dropdown">
                                        <ul class="icon-navigation">
                                            <li>
                                                <a href="#">Change your pic</a>
                                            </li>
                                            <li>
                                                <a href="#">Change your username</a>
                                            </li>
                                            <li>
                                                <a href="#">About us</a>
                                            </li>
                                            <li>
                                                <a href="#">Contact me</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!--// Profile -->
                    <!-- Browser stats -->
                    <div class="outer-w3-agile col-xl mt-3">
                        <h4 class="tittle-w3-agileits mb-4">Browser Stats</h4>
                        <div class="stats-info stats-body">
                            <ul class="list-unstyled">
                                <li class="pb-3">GoogleChrome
                                    <span class="float-right">85%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar green" style="width:85%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Firefox
                                    <span class="float-right">35%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar yellow" style="width:35%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Internet Explorer
                                    <span class="float-right">78%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar red" style="width:78%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Safari
                                    <span class="float-right">50%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar blue" style="width:50%;"></div>
                                    </div>
                                </li>
                                <li class="py-md-4 py-3">Opera
                                    <span class="float-right">80%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar light-blue" style="width:80%;"></div>
                                    </div>
                                </li>
                                <li class="last py-md-4 py-3">Others
                                    <span class="float-right">60%</span>
                                    <div class="progress progress-striped active progress-right">
                                        <div class="bar orange" style="width:60%;"></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!--// Browser stats -->
                </div>
            </div>
             <!--// Three-grids -->
            <!-- Countdown -->
            <div class="outer-w3-agile mt-3 outer-w3-agile-bg">
                <h4 class="tittle-w3-agileits mb-4 text-white">Countdown Timer</h4>
                <div class="simply-countdown-custom" id="simply-countdown-custom"></div>
            </div>



{% endblock %}

templates/admintemplates/adminlogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Login Form</title>
	<link href="{% static 'adminstatic/css//bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<div class="row bg-success mb-3">
		<div class="col-md-12">
			<h1 class="text-white text-center p-5">Login to enter admin panel</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 mx-auto p-3" style="border: 1px solid green;">
		 	<form method = "POST">
		 		{% csrf_token %}
		 		{{ form.as_p }}
		 		<button class="btn btn-primary btn-block">Login</button>
		 	</form>
		</div>
	</div>

</body>
</html>

templates/admintemplates/adminofferdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}

<h3>Offer Delete</h3>
<form method = "Post">
{% csrf_token %}
<p>Are you Sure To delete?</p>
<button class = "btn btn-danger">yes</button>
<a href="{% url 'bakaapp:adminservicelist' %}" class="btn btn-info"> No</a>
</form>

{% endblock %}

templates/admintemplates/adminofferlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'bakaapp:adminoffercreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Offers</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Title</th>
                                <th scope="col">From</th>
                                <th scope="col">To</th>
                                <th scope="col">Packages</th>
                                <th scope="col">Image</th>
                                <th scope="col">Created Date</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for offer in adminofferlist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{offer.title}}</td>
                                <td>{{offer.offer_starts}}</td>
                                <td>{{offer.offer_ends}}</td>
                                <td>{{offer.packages}}</td>
                                <td><img src="{{offer.images.url}}" width="70"></td>
                                <td>{{offer.created_at}}</td>
                                <td>
                                	<a href="{% url 'bakaapp:adminofferupdate' offer.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'bakaapp:adminofferdelete' offer.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplates/adminservicedelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}

<h3>Service Delete</h3>
<form method = "Post">
{% csrf_token %}
<p>Are you Sure To delete?</p>
<button class = "btn btn-danger">yes</button>
<a href="{% url 'bakaapp:adminservicelist' %}" class="btn btn-info"> No</a>
</form>

{% endblock %}

templates/admintemplates/adminservicelist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'bakaapp:adminservicecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Services</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Title</th>
                                <th scope="col">Image</th>
                                <th scope="col">Created at</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for service in adminservicelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{service.title}}</td>
                                <td><img src="{{service.image.url}}" width="80"></td>
                                <td>{{service.created_at}}</td>
                                <td>
                                	<a href="{% url 'bakaapp:adminserviceupdate' service.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'bakaapp:adminservicedelete' service.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplates/adminservicepackagedelete.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}

<h3>ServicePackage Delete </h3>
<form method = "Post">
{% csrf_token %}
<p>Are you Sure To delete?</p>
<button class = "btn btn-danger">yes</button>
<a href="{% url 'bakaapp:adminservicepackagelist' %}" class="btn btn-info"> No</a>
</form>

{% endblock %}

templates/admintemplates/adminservicepackagelist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'bakaapp:adminservicepackagecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Service Packages</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Service</th>
                                <th scope="col">Title</th>
                                <th scope="col">image</th>
                                <th scope="col">Rate</th>
                                <th scope="col">Durations</th>
                                <th scope="col">Created at</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for servicepackage in adminservicepackagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>

                                <td>{{servicepackage.service}}</td>
                                <td>{{servicepackage.title}}</td>
                                <td><img src="{{servicepackage.image.url}}" width="80"></td>
                                <td>{{servicepackage.rate}}</td>
                                <td>{{servicepackage.duration}}</td>
                                <td>{{servicepackage.created_at}}</td>
                                <td>
                                	<a href="{% url 'bakaapp:adminservicepackageupdate' servicepackage.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'bakaapp:adminservicepackagedelete' servicepackage.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplates/adminteamlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'bakaapp:adminteamcreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Team Members</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Name</th>
                                <th scope="col">Post</th>
                                <th scope="col">Image</th>
                                <th scope="col">Mobile</th>
                                <th scope="col">Email</th>
                                <th scope="col">Experience</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for team in adminteamlist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{team.name}}</td>
                                <td>{{service.post}}</td>
                                <td><img src="{{team.image.url}}" width="80"></td>
                                <td>{{team.mobile}}</td>
                                <td>{{service.email}}</td>
                                <td>{{service.experience}}</td>
                                <td>{{service.created_at}}</td>
                                <td>
                                	<a href="{% url 'bakaapp:adminserviceupdate' service.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'bakaapp:adminservicedelete' service.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}